### ISSUE TITLE
In MPNCOV.py Line106

### ISSUE THREAD

**Issue by duanyucat** [XuChunqiao/Tensorflow-Fast-MPNCOV#1]
In MPNCOV.py Line106 .....tf.eye(dim)...
When I run the code, there have a 'TypeError: num_rows and num_columns must be positive integer values.'
Is the 'dim' wrong?

**Comment by XuChunqiao** [comment]
I run the code using the same MPNCOV.py, but I didn't encounter this error. So I don't know what results in the ERROR, and I don't think the type of 'dim' is wrong because of _dim = x.shape[1]_, which can ensure the dim is positive integer values.
